apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vechtron-ui
  namespace: vechtron-webapp
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    acme.cert-manager.io/http01-edit-in-place: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: sandbox.vechtron.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vechtron-ui
            port:
              number: 80

  tls:
  - secretName: vechtron-ui
    hosts:
    - sandbox.vechtron.com

